apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "apache.fullname" . }}-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apache.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "apache.selectorLabels" . | nindent 6 }}