---
# ApplicationSet for cldev01 environment
# Automatically generates Applications ONLY for charts that have corresponding values files
# in environments/cldev01/values/ directory

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cldev01-workloads
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  generators:
    - git:
        repoURL: https://github.com/rsvivek25/argocd-pilot-practice
        revision: main
        files:
          - path: 'environments/cldev01/values/*.yaml'
  template:
    metadata:
      name: '{{path.basenameNormalized}}-cldev01'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      sources:
        # Source 1: Helm chart with environment-specific values
        - repoURL: https://github.com/rsvivek25/argocd-pilot-practice
          targetRevision: main
          path: 'charts/{{path.basenameNormalized}}'
          helm:
            releaseName: '{{path.basenameNormalized}}'
            valueFiles:
              - ../../environments/cldev01/values/{{path.filename}}
        # Source 2: External ConfigMaps (pipeline-generated)
        - repoURL: https://github.com/rsvivek25/argocd-pilot-practice
          targetRevision: main
          path: 'environments/cldev01/config/{{path.basenameNormalized}}'
          directory:
            recurse: false
      destination:
        server: https://kubernetes.default.svc
        namespace: cldev01
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas
